naver.client.id=ZcUWGNgvFfEl1Jhsq_pF
naver.client.secret=_E1lnh2VMo
mail.smtp.host=smtp.naver.com
mail.smtp.user=112tkwk@naver.com
mail.smtp.password=978YY38Q5XW3
recaptcha.site.key=6LcNwocsAAAAAP9ezNyQRtyuEbFVvzhZTIlgwpLV
recaptcha.secret.key=6LcNwocsAAAAAD9YnhOrGIpno-uLYr1DD22MTFuy